/* eslint-env browser */
// Im Config-Objekt werden Konstanten zum vereinfachten Zugriff in der ganzen Anwendung abgelegt.
var Config = {
    APP_NAME: "Songs Tindern",
    LOGIN_EVENT_KEY: "Login",
    USER_ID_KEY: "ID_KEY",
    SPOTIFY_API_CLIENT_ID: "7cf8fa10dea547d1ad285a00d44e61cc",
    SPOTIFY_API_SECRET: "9480fcf328434ab59d4d9c490d7d6cbb",
    REDIRECT_URI: "http://songs-tindern.herokuapp.com/resources/html/mainViews.html",
    API_REDIRECT_URI: "http://songs-tindern.herokuapp.com/",
    SPOTIFY_API_CODE_KEY: "Code",
    SPOTIFY_ACCESS_TOKEN_KEY: "Token",
    TOKEN_LIFE_TIME: "Token expires in",
    NEW_PLAYLIST_NAME_KEY: "new Playlist name",
    SPOTIFY_REFRESH_TOKEN_KEY: "Refresh Token",
    COUNTDOWN_UP_KEY: "Countdown up",
    COUNTDOWN_RESET_KEY: "reset countdown",
    REJECT_SONG_KEY: "Reject this song now",
    SKIP_AMOUNT_CHANGED_KEY: "Skip amount changed ",
    SONG_DETAILS_SHOW_CHANGED_KEY: "song details have changed",
    COUNTDOWN_CHANGED_KEY: "Countdown has changed",
    EVENT_SONG_SWIPED_KEY: "Song swiped key",
    EVENT_SONG_SWIPE_END: "Song swipe end key",
    EVENT_SPEED_MODE_SETTING_KEY: "this is the callback for the speed setting key",
    EVENT_SONG_PLAYING_KEY: "song is now playling Event key",
    EVENT_SONG_AUDIO_LOADED_KEY: "song audio is now loaded correctly key",
    EVENT_RETURN_START_MENU_KEY: "returning to start menu.. key",
    EVENT_PLAYER_RESUME_SONG_LOADED: "EVENT_PLAYER_RESUME_SONG_LOADED event key",
    CURRENT_ROUND_LIKED_SONGS_KEY: "current round liked songs key",
    SPOTIFY_CREATE_PLAYLIST_URL: "https://api.spotify.com/v1/users/$user_id/playlists",
    SPOTIFY_GET_USER_ID_URL: "https://api.spotify.com/v1/me",
    SPOTIFY_USER_PLAYLIST_LIST_URL: "https://api.spotify.com/v1/me/playlists?limit=50",
    SPOTIFY_ADD_ITEM_TO_PLAYLIST_URL: "https://api.spotify.com/v1/playlists/$playlist_id/tracks?uris=$uris",
    SPOTIFY_ADD_MULTIPLE_ITEMS_TO_PLAYLIST_URL: "https://api.spotify.com/v1/playlists/$playlist_id/tracks",
    PLAYLIST_ID_KEY:"PLAYLIST_ID",
    BASE_URL_KEY: "Base URL",
    ALL_LETTERS: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "ä", "ü", "ö"],
    SPOTIFY_SEARCH_URL: "https://api.spotify.com/v1/search?query=$randomQuery&offset=$randomOffset&limit=1&type=track&market=DE",
    SEARCH_CALLBACK_EVENT: "Search",
    SPOTIFY_DEVICE_ID_KEY: "Device",
    SPOTIFY_PAUSE_URL: "https://api.spotify.com/v1/me/player/pause?device_id=$device",
    SPOTIFY_QUEUE_URL: "https://api.spotify.com/v1/me/player/queue?device_id=$device?uri=$songuri",
    SPOTIFY_NEXT_URL: "https://api.spotify.com/v1/me/player/next?device_id=$device",
    SPOTIFY_PLAY_URL: "https://api.spotify.com/v1/me/player/play?device_id=$device",
    SPOTIFY_GET_ARTIST_URL: "https://api.spotify.com/v1/artists/$id",
    SPOTIFY_SEEK_TO_POS_URL: "https://api.spotify.com/v1/me/player/seek?position_ms=$position",
    SONG_READY_EVENT: "Ready to play",
    SONG_SHOWABLE_EVENT: "Show Song",
    SWIPED_SONGS_HISTORY_KEY: "Swiped Songs",
    SONG_COUNT_KEY: "Song Count",
    DEFAULT_SPEED_ROUND_DURATION: 26000,
    DEFAULT_RANDOM_ROUND_DURATION: 9000,
    DEFAULT_HARD_ROUND_DURATION: 8000,
    DEFAULT_TICK_SPEED: 1000,
    DEFAULT_SONG_SKIPS_AMOUNT: 3,
    DEFAULT_SKIP_DELAY_FOR_LOADING: 850,
    DEFAULT_PLAYLIST_NAME: "SongsTinderPlaylist",
    DEFAULT_SHOW_SKIP_TEXT_TIME: 1500,
    DEFAULT_ICON_BAR_TEXT: "Swipe History",
    LIKE_COUNTER_KEY: "Likecounter",
    DISLIKE_COUNTER_KEY: "Dislikecounter",
    GENRE_LIST_KEY: "Genrelist",
    SONG_TITLE_KEY: "title",
    SONG_INTERPRET_KEY: "interpret",
    SONG_COVER_KEY: "cover",
    SPEED_ROUND_TYPE_RANDOM_KEY: "randomCountdown",
    SPEED_ROUND_TYPE_HIDDEN_KEY: "hiddenCountdown",
    SPEED_ROUND_TYPE_HARD_KEY: "hardCountdown",
    NORMAL_MODE_KEY: "normal",
    HIDDEN_MODE_KEY: "hidden",
    RANDOM_MODE_KEY: "random",
    HARD_MODE_KEY: "hard",
    DEFAULT_COUNTDOWN_NUMBER_OFFSET: 3,
    DEFAULT_COUNTDOWN_NUMBER: 4,
    DEFAULT_SONG_COVER_PATH: "../icons/hidden_mode_icon_v1.png",
    ARTIST_INFO_EVENT: "Artist Info ready",
    PLAYLIST_NAME_KEY: "Playlist name",
    SPOTIFY_PLAYLIST_CONTEXT: "spotify:playlist:$id",
    LIKE_TIMEOUT: 850,
    SPOTIFY_SONG_DETAILS_URL: "https://api.spotify.com/v1/audio-features/$id",
    SONG_DETAILS_EVENT: "Song Details loaded",
    DANCE_IMAGE_0_2: "../icons/standing_almost_still_gif.gif",
    DANCE_IMAGE_0_5: "../icons/gangnamstyle_gif.gif",
    DANCE_IMAGE_0_75: "../icons/keith_haring_gif_v2.gif",
    DANCE_IMAGE_0_9: "../icons/breakdance_green.gif",
    DANCE_IMAGE_1_0: "../icons/breakdance.gif",
    PAUSED_KEY: "Is Paused",
    PLAYER_READY_CALLBACK_KEY: "Player ready",
    CHANGED_TO_HISTORY_VIEW: "history_ready_key",
    CHANGED_TO_SWIPE_VIEW: "swipe_ready_key",
    CHANGED_TO_STATISTICS_VIEW: "statistics_ready_key",
    CHANGED_TO_START_VIEW: "start_ready_key",
    CHANGED_TO_SETTINGS_SPEED: "Settings Speed",
    CHANGED_TO_SETTINGS_DETAILS: "Settings Details",
    ADDED_ICON_BAR: "added-icon-bar",
    TINDER_CARD_TEMPLATE_READY: "Tindercard ready",
    HISTORY_CARD_TEMPLATE_READY: "Historycard ready",
    ACCESS_GRANTS: "&scope=user-read-private user-read-email user-modify-playback-state user-read-playback-position user-library-read streaming user-read-playback-state user-read-recently-played playlist-read-private playlist-modify-public playlist-modify-private playlist-read-collaborative",
    GENRE_BAR_CHART_CONFIG: {
        type: "bar",
        data: {
            labels: undefined,
            datasets: undefined,
        },
        options: {
            maintainAspectRatio: false,
            responsive: true,
            legend: {
                display: false,
                onClick: (e) => e.stopPropagation(),
                labels: {
                    fontColor: "rgb(255, 255, 255)",
                    fontSize: 20,
                },
            },
            title: {
                display: true,
                text: "Swiperate for top 4 genres",
                fontColor: "rgb(255, 255, 255)",
                fontSize: 23,
                fontFamily: "Candara",
            },
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        display: false,
                        suggestedMax: 1,
                    },
                    gridLines: { color: "rgba(0, 0, 0, 0)" },
                }],
                xAxes: [
                    {
                        gridLines: { tickMarkLength: 0 },
                        ticks: {
                            fontColor: "rgb(255, 255, 255)",
                            fontFamily: "Candara Light",
                            fontSize: 17,
                            padding: 11,
                        },
                    },
                ],
            },
        },
    },
    GENRE_BAR_CHART_DATASET: {
        data: undefined,
        backgroundColor: [
            "rgba(222, 102, 87, 1)",
            "rgba(51, 215, 255, 1)",
            "rgba(255, 189, 51, 1)",
            "rgba(92, 196, 76, 1)",
        ],
        borderWidth: 2,
        borderRadius: 2,
        borderSkipped: false,
    },
    DONUT_CHART_CONFIG: {
        type: "doughnut",
        data: {
            labels: undefined,
            datasets: undefined,
        },
        options: {
            maintainAspectRatio: false,
            responsive: true,
            legend: {
                reverse: true,
                onClick: (e) => e.stopPropagation(),
                labels: {
                    fontColor: "rgb(255, 255, 255)",
                    fontFamily: "Candara Light",
                    "fontSize": 18,
                },
            },
            plugins: {
                title: {
                    display: true,
                    text: "Chart.js Doughnut Chart",
                },
            },
        },
    },
    INSTRUMENTAL_VOCAL_DATASET: {
        label: "Rather instrumental vs rather Vocal Songs",
        data: undefined,
        backgroundColor: [
            "rgba(126, 62, 227, 1)",
            "rgba(255, 189, 51, 1)",
        ],
        borderWidth: 1,
    },
    ACOUSTIC_ELECTRONIC_DATASET: {
        label: "Rather Acoustic vs Electronic",
        data: undefined,
        backgroundColor: [
            "rgba(223, 117, 61, 1)",
            "rgba(51, 215, 255, 1)",
        ],
        borderWidth: 1,
    },
    LEFT_RIGHT_DATASET: {
        label: "Swiped Left vs Right",
        data: undefined,
        backgroundColor: [
            "rgba(92, 196, 76, 1)",
            "rgba(222, 102, 87, 1)",
        ],
        borderWidth: 1,
    },
    PLAYLIST_SELECTION_EVENT_KEY: "Plalist Selection View",
    END_SWIPE_BUTTON_CLICKED: "End Swipe",
    PLAYLISTS_KEY: "Playlists",
    PLAYLIST_READY_EVENT: "PlaylistReady",
    TOGGLE_ICON_BAR_EVENT: "Toggle Icons",
    PLAYLIST_SELECTION_SONG_TEMPLATE_READY_EVENT: "Song Template Ready",
    PLAYLIST_SELECTION_PLAYLIST_TEMPLATE_READY_EVENT: "Playlist Template Ready",
    PLAYLIST_NAME_DEFAULT: "Liked but not in Playlist",
    IS_FROM_HISTORY_KEY: "From History",
    TOAST_DURATION_IN_MS: 2000,
    GAME_RUNNING_KEY: "Game running",
    GAMEMODE_KEY: "Gamemode is",
    GAME_STATE_KEY: "Game state",
    START_ANIMATION_TIME: 5,
    ONE_SECOND: 1000,
    TEN_SECONDS: 10,
    NUMBER_GENRES_SWIPERATE: 4,
    SHORTEN_STRING_VALUE: 2,
    TOAST_TIME: 4000,
    ROUNDING_VALUE_HUNDRED: 100,
    DOUGHNUT_CHART_DEFAULT_VALUE:0.5,
    BARELY_MOVING_GIF_VALUE: 0.2,
    GANGNAM_STYLE_GIF_VALUE: 0.5,
    BREAKDANCE_GIF_GREEN_VALUE: 0.75,
    BREAKDANCE_GIF_BLUE_VALUE: 0.9,
    MIN_WIDTH_DISPLAYING_PLAYING_SONG: 1025,
    MIN_WIDTH_DISPLAYING_INFOS: 1025,
    MAX_RANDOM_NUMBER: 1000,
    SPLIT_VALUE_FOR_ACOUSTICNESS: 0.5,
    SPLIT_VALUE_FOR_INSTRUMENTALNESS: 0.5,
    TIMEOUT: 300,
    MAX_NUMBER_CARDS: 3,
    TRANSFORM_VALUE: 20,
    MAX_CHILD_CARD_COUNTER: 2,
    MAX_CARD_TITLE_LENGTH: 36,
    MAX_CARD_INTERPRET_LENGTH:20,
    MOVEMENT_X_VALUE:0.03,
    MOVEMENT_Y_VALUE: 80,
    Y_VALUE: 80,
    X_VALUE: 0.5,
    TWENTY_SECONDS_IN_MILLISECONDS: 20000,
    FIVE_SECONDS_IN_MILLISECONDS: 5000,
    WIDTH_MULTIPLY_VALUE: 1.5,
    POSITION_DISLIKE_VALUE: -50,
    POSITION_LIKE_VALUE: 50,
    STATUS_CODE_AUTH_EXPIRED: 401,
    STATUS_CODE_OKAY: 200,
    STATUS_CODE_CREATED: 201,
    STATUS_CODE_NO_CONTENT: 204,
    STATUS_CODE_NOT_FOUND: 404,
    STATUS_CODE_NOT_PREMIUM: 403,
    STATUS_CODE_BAD_GATEWAY: 502,
    STATUS_CODE_TO_MANY_REQUESTS: 429,
    MAX_PLAYLIST_REQUEST_SONGS: 49,
    SECONDS_TO_MILISECONDS_MULTIPLIER: 1000,
    SEEK_POSITION_TIMEOUT_TIME: 200,
    ONE_DAY_IN_MS: 14400000, 
    LIKE_EVENT: "LIKE EVENT",
    DISLIKE_EVENT: "DISLIKE EVENT",
    KEY_SORT_TITLE: "title",
    KEY_SORT_GENRE: "genre",
    KEY_SORT_INTERPRET: "interpret",
    KEY_SORT_PLAYLIST: "playlist",
    ARROW_LEFT_KEY: "ArrowLeft",
    ARROW_RIGHT_KEY: "ArrowRight",
    LACK_OF_INTERACTION_ERROR: "Browser prevented autoplay due to lack of interaction",
};

export default Config;